[package]
name = "blockchain"
version = "0.1.0"
authors = ["Lucas Vieira <lucasvieira@protonmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
rust-crypto = "0.2.36"